Node:
    sim: false
    ft_pub_freq: 200
    ft_pull_freq: 800
    sensor_frame: "fts_reference_link"
    transform_frame: "fts_base_link"

Calibration:
    Offset:
        n_measurements: 500
        T_between_meas: 0.01
        isStatic: false # true= use static offset Calibration, false=use calibrate Sensor to 0 in current State

ThresholdFilter:
  linear_threshold: 2.5
  angular_threshold: 0.3

LowPassFilter:
    Force_x:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0
    Force_y:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0
    Force_z:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0
    Torque_x:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0
    Torque_y:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0
    Torque_z:
        SamplingFrequency: 200.0
        DampingFrequency: 15.0
        DampingIntensity: -6.0

MovingMeanFilter:
    Force_x:
        divider: 4
    Force_y:
        divider: 4
    Force_z:
        divider: 4
    Torque_x:
        divider: 4
    Torque_y:
        divider: 4
    Torque_z:
        divider: 4

GravityCompensation:
    #CoG:
     #x: 0
     #y: 0
     #z: 0.027346102 # m
    #force: 7.9459955 # f_G
    world_frame: "base_link"

Publish:
    sensor_data: true
    low_pass: true
    moving_mean: true
    transformed_data: true
    gravity_compensated: true
    threshold_filtered: true
